DROP SEQUENCE SEQ_FOURNISSEUR;
DROP SEQUENCE SEQ_MEDECIN;
DROP SEQUENCE SEQ_COMMANDE;
DROP SEQUENCE SEQ_ALLERGIE;
DROP SEQUENCE SEQ_PATIENT;
DROP SEQUENCE SEQ_ETAT;
DROP SEQUENCE SEQ_CENTRE_DE_GESTION;
DROP SEQUENCE SEQ_ORDONNANCE;
DROP SEQUENCE SEQ_MUTUEL;
DROP SEQUENCE SEQ_CLASSE_PHARMACEUTIQUE;


CREATE SEQUENCE SEQ_FOURNISSEUR;

CREATE OR REPLACE TRIGGER INCR_FOURNISSEUR
BEFORE INSERT ON FOURNISSEUR
FOR EACH ROW

BEGIN
	SELECT SEQ_FOURNISSEUR.NEXTVAL
	INTO :new.FOU_ID
	FROM DUAL;
END; 
/


CREATE SEQUENCE SEQ_MEDECIN;

CREATE OR REPLACE TRIGGER INCR_MEDECIN
BEFORE INSERT ON MEDECIN
FOR EACH ROW

BEGIN
	SELECT SEQ_MEDECIN.NEXTVAL
	INTO :new.MED_ID
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_COMMANDE;

CREATE OR REPLACE TRIGGER INCR_COMMANDE
BEFORE INSERT ON COMMANDE
FOR EACH ROW

BEGIN
	SELECT SEQ_COMMANDE.NEXTVAL
	INTO :new.COM_ID
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_ALLERGIE;

CREATE OR REPLACE TRIGGER INCR_ALLERGIE
BEFORE INSERT ON ALLERGIE
FOR EACH ROW

BEGIN
	SELECT SEQ_ALLERGIE.NEXTVAL
	INTO :new.ALL_ID
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_PATIENT;

CREATE OR REPLACE TRIGGER INCR_PATIENT
BEFORE INSERT ON PATIENT
FOR EACH ROW

BEGIN
	SELECT SEQ_PATIENT.NEXTVAL
	INTO :new.PAT_NUM
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_ETAT;

CREATE OR REPLACE TRIGGER INCR_ETAT
BEFORE INSERT ON ETAT
FOR EACH ROW

BEGIN
	SELECT SEQ_ETAT.NEXTVAL
	INTO :new.ETAT_ID
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_CENTRE_DE_GESTION;

CREATE OR REPLACE TRIGGER INCR_CENTRE_DE_GESTION
BEFORE INSERT ON CENTRE_DE_GESTION
FOR EACH ROW

BEGIN
	SELECT SEQ_CENTRE_DE_GESTION.NEXTVAL
	INTO :new.CDG_ID
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_ORDONNANCE;

CREATE OR REPLACE TRIGGER INCR_ORDONNANCE
BEFORE INSERT ON ORDONNANCE
FOR EACH ROW

BEGIN
	SELECT SEQ_ORDONNANCE.NEXTVAL
	INTO :new.ORD_NUM
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_MUTUEL;

CREATE OR REPLACE TRIGGER INCR_MUTUEL
BEFORE INSERT ON MUTUEL
FOR EACH ROW

BEGIN
	SELECT SEQ_MUTUEL.NEXTVAL
	INTO :new.MUT_ID
	FROM DUAL;
END; 
/

CREATE SEQUENCE SEQ_CLASSE_PHARMACEUTIQUE;

CREATE OR REPLACE TRIGGER INCR_CLASSE_PHARMACEUTIQUE
BEFORE INSERT ON CLASSE_PHARMACEUTIQUE
FOR EACH ROW

BEGIN
	SELECT SEQ_CLASSE_PHARMACEUTIQUE.NEXTVAL
	INTO :new.CPH_ID
	FROM DUAL;
END; 
/